services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sys25\RnBase\:
    resource: '../Classes/*'
    exclude: [
      '../Classes/Domain/Model/*',
      '../Classes/Constants.php',
      '../Classes/class.tx_rnbase.php',
      '../Classes/Typo3Wrapper/*',
      '../Classes/Testing/*'
    ]

  Sys25\RnBase\Frontend\Controller\MainController:
    public: true

  tx_rnbase_controller:
    alias: Sys25\RnBase\Frontend\Controller\MainController
    public: true

  Sys25\RnBase\Frontend\View\Factory:
    public: true

  Sys25\RnBase\Backend\Module\ModFuncFrame:
    public: true

  Sys25\RnBase\Domain\Repository\RepositoryRegistry:
    public: true
