services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sys25\RnBase\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/Model/*', '../Classes/Constants.php', '../Classes/class.tx_rnbase.php', '../Classes/Typo3Wrapper/*']

  Sys25\RnBase\Backend\Module\ModFuncFrame:
    public: true