services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sys25\RnBase\:
    resource: '../Classes/*'
    exclude: [
      '../Classes/Domain/Model/*',
      '../Classes/Constants.php',
      '../Classes/class.tx_rnbase.php',
      '../Classes/Typo3Wrapper/*',
      '../Classes/Testing/*'
    ]

  Sys25\RnBase\Backend\Module\ModFuncFrame:
    public: true

  # Geht vorerst nicht anders. Nur intern zu verwenden!
  Sys25\RnBase\Frontend\Provider\FrontendServiceProvider:
    public: true
