<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'Doctrine\\Common\\Collections\\' => [$vendorDir . '/doctrine/collections/lib'],
];
