name: PHP Checks

on: [push, pull_request]

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                ref: ${{ github.ref }}
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
            - run: composer require friendsofphp/php-cs-fixer
            - run: .Build/bin/php-cs-fixer fix --diff --dry-run
